@startuml titre Manipulation de lampes

'''classes
class Lampe {
    -nom : String
    -allumee : boolean

    +Lampe(nom)
    +allumer()
    +eteindre()
    +toString() : String
}

class Hifi{
    +son : int;

    +allumer()
    +eteindre()
    +toString(): String
}

class Telecommande {

    +Telecommande()
    +ajouterLampe(l)
    +ajouterHifi(h)
    +activerLampe(indiceLampe)
    +activerHifi(indiceHifi)
    +desactiverLampe(indiceLampe)
    +desactiverHifi(indiceHifi)
    +activerToutLampe()
    +activerToutHifi()
    +toString() : String
}

'''relations
Telecommande "1" --> "*" Lampe : -lampes
Telecommande "1" --> "*" Hifi : -hifis

@enduml